LEFT_MIN_W = 380
LEFT_DEFAULT_W = 490
RIGHT_MIN_W = 500

ROOT_MARGINS = (6, 6, 6, 6)
LEFT_MARGINS = (6, 6, 6, 6)
RIGHT_MARGINS = (6, 6, 6, 6)

PANEL_SPACING = 8
ROOT_SPACING = 0

CONTROL_HEIGHT = 30
PREVIEW_FIT_BUTTON_H = 28
PREVIEW_FIT_BUTTON_W = 56
PREVIEW_MIN_H = 420
PREVIEW_VIEWPORT_STYLE = "QGraphicsView { background: #ffffff; border: 1px solid #dddddd; border-radius: 4px; }"
STATUS_PANEL_H = 120
PROJECT_LABEL_W = 70
PROJECT_MARGINS = (8, 8, 8, 8)
PROJECT_H_SPACING = 8
PROJECT_V_SPACING = 6
